version: "3.7"
services:
  api:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    command: npm run start:dev