version: "3.7"
services:
  api:
    image: node:13-alpine
    volumes:
      - ./src:/src
      - ./package.json:/package.json
      - ./index.ts:/index.ts
      - ./tsconfig.json:/tsconfig.json
      - ./node_modules:/node_modules
    ports:
      - "3000:3000"
    entrypoint: npm run start:dev